/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockRitualSystemSol from './MockRitualSystem.sol/index.js';
export type { mockRitualSystemSol };