/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IExecutableWatcher, IExecutableWatcherInterface } from "../../../test/MockRitualSystem.sol/IExecutableWatcher.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "executionIndex",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "assetId",
        "type": "bytes32"
      }
    ],
    "name": "executeAnalysis",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "executionIndex",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "assetId",
        "type": "bytes32"
      }
    ],
    "name": "executeFetch",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IExecutableWatcher__factory {
    static readonly abi = _abi;
    static createInterface(): IExecutableWatcherInterface {
      return new Interface(_abi) as IExecutableWatcherInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IExecutableWatcher {
      return new Contract(address, _abi, runner) as unknown as IExecutableWatcher;
    }
  }
  