/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IScheduler, ISchedulerInterface } from "../../SentimentOracle.sol/IScheduler.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "callId",
        "type": "uint256"
      }
    ],
    "name": "cancel",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      },
      {
        "internalType": "uint32",
        "name": "gas",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "startBlock",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "numCalls",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "frequency",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "ttl",
        "type": "uint32"
      },
      {
        "internalType": "uint256",
        "name": "maxFeePerGas",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "maxPriorityFeePerGas",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "payer",
        "type": "address"
      }
    ],
    "name": "schedule",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "callId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IScheduler__factory {
    static readonly abi = _abi;
    static createInterface(): ISchedulerInterface {
      return new Interface(_abi) as ISchedulerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IScheduler {
      return new Contract(address, _abi, runner) as unknown as IScheduler;
    }
  }
  