/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ISchedulerInterface extends Interface {
    getFunction(nameOrSignature: "cancel" | "getCallState" | "schedule"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'cancel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCallState', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'schedule', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'cancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCallState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'schedule', data: BytesLike): Result;
  }

  

  export interface IScheduler extends BaseContract {
    
    connect(runner?: ContractRunner | null): IScheduler;
    waitForDeployment(): Promise<this>;

    interface: ISchedulerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancel: TypedContractMethod<
      [callId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCallState: TypedContractMethod<
      [callId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    schedule: TypedContractMethod<
      [data: BytesLike, gas: BigNumberish, startBlock: BigNumberish, numCalls: BigNumberish, frequency: BigNumberish, ttl: BigNumberish, maxFeePerGas: BigNumberish, maxPriorityFeePerGas: BigNumberish, value: BigNumberish, payer: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancel'): TypedContractMethod<
      [callId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCallState'): TypedContractMethod<
      [callId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'schedule'): TypedContractMethod<
      [data: BytesLike, gas: BigNumberish, startBlock: BigNumberish, numCalls: BigNumberish, frequency: BigNumberish, ttl: BigNumberish, maxFeePerGas: BigNumberish, maxPriorityFeePerGas: BigNumberish, value: BigNumberish, payer: AddressLike, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }