/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ScheduledMarketWatcher {
      
    export type AssetConfigStruct = {symbol: string, coinId: string, httpExecutor: AddressLike, llmExecutor: AddressLike, fetchScheduleId: BigNumberish, analysisScheduleId: BigNumberish, configured: boolean}

    export type AssetConfigStructOutput = [symbol: string, coinId: string, httpExecutor: string, llmExecutor: string, fetchScheduleId: bigint, analysisScheduleId: bigint, configured: boolean] & {symbol: string, coinId: string, httpExecutor: string, llmExecutor: string, fetchScheduleId: bigint, analysisScheduleId: bigint, configured: boolean }
  

    export type MarketSnapshotStruct = {symbol: string, summary: string, bodyHash: BytesLike, statusCode: BigNumberish, bodySize: BigNumberish, errorMessage: string, fetchedAt: BigNumberish, fetchExecutionIndex: BigNumberish, available: boolean}

    export type MarketSnapshotStructOutput = [symbol: string, summary: string, bodyHash: string, statusCode: bigint, bodySize: bigint, errorMessage: string, fetchedAt: bigint, fetchExecutionIndex: bigint, available: boolean] & {symbol: string, summary: string, bodyHash: string, statusCode: bigint, bodySize: bigint, errorMessage: string, fetchedAt: bigint, fetchExecutionIndex: bigint, available: boolean }
  

    export type SentimentResultStruct = {symbol: string, score: BigNumberish, signal: string, reasoning: string, rawResponse: string, errorMessage: string, model: string, executor: AddressLike, analyzedAt: BigNumberish, analysisExecutionIndex: BigNumberish, snapshotTimestamp: BigNumberish, fulfilled: boolean, hasError: boolean}

    export type SentimentResultStructOutput = [symbol: string, score: bigint, signal: string, reasoning: string, rawResponse: string, errorMessage: string, model: string, executor: string, analyzedAt: bigint, analysisExecutionIndex: bigint, snapshotTimestamp: bigint, fulfilled: boolean, hasError: boolean] & {symbol: string, score: bigint, signal: string, reasoning: string, rawResponse: string, errorMessage: string, model: string, executor: string, analyzedAt: bigint, analysisExecutionIndex: bigint, snapshotTimestamp: bigint, fulfilled: boolean, hasError: boolean }
  
    }

  export interface ScheduledMarketWatcherInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_MAX_COMPLETION_TOKENS" | "DEFAULT_MODEL" | "DEFAULT_TEMPERATURE" | "HTTP_PRECOMPILE" | "HTTP_TTL" | "JQ_PRECOMPILE" | "LLM_PRECOMPILE" | "LLM_TTL" | "RITUAL_WALLET" | "SCHEDULER_ADDRESS" | "analyzeNow" | "assetIdFor" | "cancelAssetWatcher" | "configureAsset" | "depositScheduleFees" | "executeAnalysis" | "executeFetch" | "fetchNow" | "getAssetConfig" | "getMarketSnapshot" | "getSentimentResult" | "owner" | "scheduleAssetWatcher" | "scheduler" | "totalTrackedAssets" | "trackedAssets" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AssetConfigured" | "MarketSnapshotUpdated" | "ScheduleFeesDeposited" | "SentimentAnalyzed" | "WatcherCancelled" | "WatcherScheduled"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_MAX_COMPLETION_TOKENS', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_MODEL', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_TEMPERATURE', values?: undefined): string;
encodeFunctionData(functionFragment: 'HTTP_PRECOMPILE', values?: undefined): string;
encodeFunctionData(functionFragment: 'HTTP_TTL', values?: undefined): string;
encodeFunctionData(functionFragment: 'JQ_PRECOMPILE', values?: undefined): string;
encodeFunctionData(functionFragment: 'LLM_PRECOMPILE', values?: undefined): string;
encodeFunctionData(functionFragment: 'LLM_TTL', values?: undefined): string;
encodeFunctionData(functionFragment: 'RITUAL_WALLET', values?: undefined): string;
encodeFunctionData(functionFragment: 'SCHEDULER_ADDRESS', values?: undefined): string;
encodeFunctionData(functionFragment: 'analyzeNow', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'assetIdFor', values: [string]): string;
encodeFunctionData(functionFragment: 'cancelAssetWatcher', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'configureAsset', values: [string, string, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'depositScheduleFees', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'executeAnalysis', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'executeFetch', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'fetchNow', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAssetConfig', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMarketSnapshot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSentimentResult', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'scheduleAssetWatcher', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'scheduler', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalTrackedAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'trackedAssets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_MAX_COMPLETION_TOKENS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_MODEL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_TEMPERATURE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HTTP_PRECOMPILE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HTTP_TTL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'JQ_PRECOMPILE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LLM_PRECOMPILE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LLM_TTL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RITUAL_WALLET', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SCHEDULER_ADDRESS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'analyzeNow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assetIdFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelAssetWatcher', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'configureAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositScheduleFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeAnalysis', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeFetch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fetchNow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAssetConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarketSnapshot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSentimentResult', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'scheduleAssetWatcher', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'scheduler', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTrackedAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trackedAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace AssetConfiguredEvent {
      export type InputTuple = [assetId: BytesLike, symbol: string, coinId: string, httpExecutor: AddressLike, llmExecutor: AddressLike];
      export type OutputTuple = [assetId: string, symbol: string, coinId: string, httpExecutor: string, llmExecutor: string];
      export interface OutputObject {assetId: string, symbol: string, coinId: string, httpExecutor: string, llmExecutor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketSnapshotUpdatedEvent {
      export type InputTuple = [assetId: BytesLike, symbol: string, executionIndex: BigNumberish, statusCode: BigNumberish, available: boolean];
      export type OutputTuple = [assetId: string, symbol: string, executionIndex: bigint, statusCode: bigint, available: boolean];
      export interface OutputObject {assetId: string, symbol: string, executionIndex: bigint, statusCode: bigint, available: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScheduleFeesDepositedEvent {
      export type InputTuple = [amount: BigNumberish, lockBlocks: BigNumberish];
      export type OutputTuple = [amount: bigint, lockBlocks: bigint];
      export interface OutputObject {amount: bigint, lockBlocks: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SentimentAnalyzedEvent {
      export type InputTuple = [assetId: BytesLike, symbol: string, executionIndex: BigNumberish, hasError: boolean, score: BigNumberish, signal: string, model: string];
      export type OutputTuple = [assetId: string, symbol: string, executionIndex: bigint, hasError: boolean, score: bigint, signal: string, model: string];
      export interface OutputObject {assetId: string, symbol: string, executionIndex: bigint, hasError: boolean, score: bigint, signal: string, model: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WatcherCancelledEvent {
      export type InputTuple = [assetId: BytesLike, fetchScheduleId: BigNumberish, analysisScheduleId: BigNumberish];
      export type OutputTuple = [assetId: string, fetchScheduleId: bigint, analysisScheduleId: bigint];
      export interface OutputObject {assetId: string, fetchScheduleId: bigint, analysisScheduleId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WatcherScheduledEvent {
      export type InputTuple = [assetId: BytesLike, fetchScheduleId: BigNumberish, analysisScheduleId: BigNumberish, cadence: BigNumberish, analysisDelay: BigNumberish];
      export type OutputTuple = [assetId: string, fetchScheduleId: bigint, analysisScheduleId: bigint, cadence: bigint, analysisDelay: bigint];
      export interface OutputObject {assetId: string, fetchScheduleId: bigint, analysisScheduleId: bigint, cadence: bigint, analysisDelay: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ScheduledMarketWatcher extends BaseContract {
    
    connect(runner?: ContractRunner | null): ScheduledMarketWatcher;
    waitForDeployment(): Promise<this>;

    interface: ScheduledMarketWatcherInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_MAX_COMPLETION_TOKENS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFAULT_MODEL: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_TEMPERATURE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    HTTP_PRECOMPILE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    HTTP_TTL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    JQ_PRECOMPILE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    LLM_PRECOMPILE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    LLM_TTL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RITUAL_WALLET: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SCHEDULER_ADDRESS: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    analyzeNow: TypedContractMethod<
      [assetId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    assetIdFor: TypedContractMethod<
      [symbol: string, ],
      [string],
      'view'
    >
    

    
    cancelAssetWatcher: TypedContractMethod<
      [assetId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    configureAsset: TypedContractMethod<
      [symbol: string, coinId: string, httpExecutor: AddressLike, llmExecutor: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    depositScheduleFees: TypedContractMethod<
      [lockBlocks: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    executeAnalysis: TypedContractMethod<
      [executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    executeFetch: TypedContractMethod<
      [executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    fetchNow: TypedContractMethod<
      [assetId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getAssetConfig: TypedContractMethod<
      [assetId: BytesLike, ],
      [ScheduledMarketWatcher.AssetConfigStructOutput],
      'view'
    >
    

    
    getMarketSnapshot: TypedContractMethod<
      [assetId: BytesLike, ],
      [ScheduledMarketWatcher.MarketSnapshotStructOutput],
      'view'
    >
    

    
    getSentimentResult: TypedContractMethod<
      [assetId: BytesLike, ],
      [ScheduledMarketWatcher.SentimentResultStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    scheduleAssetWatcher: TypedContractMethod<
      [assetId: BytesLike, cadence: BigNumberish, analysisDelay: BigNumberish, numCalls: BigNumberish, gasLimit: BigNumberish, schedulerTtl: BigNumberish, maxFeePerGas: BigNumberish, maxPriorityFeePerGas: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    scheduler: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalTrackedAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    trackedAssets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_MAX_COMPLETION_TOKENS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_MODEL'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_TEMPERATURE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'HTTP_PRECOMPILE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'HTTP_TTL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'JQ_PRECOMPILE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'LLM_PRECOMPILE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'LLM_TTL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RITUAL_WALLET'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SCHEDULER_ADDRESS'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'analyzeNow'): TypedContractMethod<
      [assetId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'assetIdFor'): TypedContractMethod<
      [symbol: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelAssetWatcher'): TypedContractMethod<
      [assetId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'configureAsset'): TypedContractMethod<
      [symbol: string, coinId: string, httpExecutor: AddressLike, llmExecutor: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositScheduleFees'): TypedContractMethod<
      [lockBlocks: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'executeAnalysis'): TypedContractMethod<
      [executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeFetch'): TypedContractMethod<
      [executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fetchNow'): TypedContractMethod<
      [assetId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAssetConfig'): TypedContractMethod<
      [assetId: BytesLike, ],
      [ScheduledMarketWatcher.AssetConfigStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMarketSnapshot'): TypedContractMethod<
      [assetId: BytesLike, ],
      [ScheduledMarketWatcher.MarketSnapshotStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSentimentResult'): TypedContractMethod<
      [assetId: BytesLike, ],
      [ScheduledMarketWatcher.SentimentResultStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'scheduleAssetWatcher'): TypedContractMethod<
      [assetId: BytesLike, cadence: BigNumberish, analysisDelay: BigNumberish, numCalls: BigNumberish, gasLimit: BigNumberish, schedulerTtl: BigNumberish, maxFeePerGas: BigNumberish, maxPriorityFeePerGas: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'scheduler'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalTrackedAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'trackedAssets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AssetConfigured'): TypedContractEvent<AssetConfiguredEvent.InputTuple, AssetConfiguredEvent.OutputTuple, AssetConfiguredEvent.OutputObject>;
getEvent(key: 'MarketSnapshotUpdated'): TypedContractEvent<MarketSnapshotUpdatedEvent.InputTuple, MarketSnapshotUpdatedEvent.OutputTuple, MarketSnapshotUpdatedEvent.OutputObject>;
getEvent(key: 'ScheduleFeesDeposited'): TypedContractEvent<ScheduleFeesDepositedEvent.InputTuple, ScheduleFeesDepositedEvent.OutputTuple, ScheduleFeesDepositedEvent.OutputObject>;
getEvent(key: 'SentimentAnalyzed'): TypedContractEvent<SentimentAnalyzedEvent.InputTuple, SentimentAnalyzedEvent.OutputTuple, SentimentAnalyzedEvent.OutputObject>;
getEvent(key: 'WatcherCancelled'): TypedContractEvent<WatcherCancelledEvent.InputTuple, WatcherCancelledEvent.OutputTuple, WatcherCancelledEvent.OutputObject>;
getEvent(key: 'WatcherScheduled'): TypedContractEvent<WatcherScheduledEvent.InputTuple, WatcherScheduledEvent.OutputTuple, WatcherScheduledEvent.OutputObject>;

    filters: {
      
      'AssetConfigured(bytes32,string,string,address,address)': TypedContractEvent<AssetConfiguredEvent.InputTuple, AssetConfiguredEvent.OutputTuple, AssetConfiguredEvent.OutputObject>;
      AssetConfigured: TypedContractEvent<AssetConfiguredEvent.InputTuple, AssetConfiguredEvent.OutputTuple, AssetConfiguredEvent.OutputObject>;
    

      'MarketSnapshotUpdated(bytes32,string,uint256,uint16,bool)': TypedContractEvent<MarketSnapshotUpdatedEvent.InputTuple, MarketSnapshotUpdatedEvent.OutputTuple, MarketSnapshotUpdatedEvent.OutputObject>;
      MarketSnapshotUpdated: TypedContractEvent<MarketSnapshotUpdatedEvent.InputTuple, MarketSnapshotUpdatedEvent.OutputTuple, MarketSnapshotUpdatedEvent.OutputObject>;
    

      'ScheduleFeesDeposited(uint256,uint256)': TypedContractEvent<ScheduleFeesDepositedEvent.InputTuple, ScheduleFeesDepositedEvent.OutputTuple, ScheduleFeesDepositedEvent.OutputObject>;
      ScheduleFeesDeposited: TypedContractEvent<ScheduleFeesDepositedEvent.InputTuple, ScheduleFeesDepositedEvent.OutputTuple, ScheduleFeesDepositedEvent.OutputObject>;
    

      'SentimentAnalyzed(bytes32,string,uint256,bool,int8,string,string)': TypedContractEvent<SentimentAnalyzedEvent.InputTuple, SentimentAnalyzedEvent.OutputTuple, SentimentAnalyzedEvent.OutputObject>;
      SentimentAnalyzed: TypedContractEvent<SentimentAnalyzedEvent.InputTuple, SentimentAnalyzedEvent.OutputTuple, SentimentAnalyzedEvent.OutputObject>;
    

      'WatcherCancelled(bytes32,uint256,uint256)': TypedContractEvent<WatcherCancelledEvent.InputTuple, WatcherCancelledEvent.OutputTuple, WatcherCancelledEvent.OutputObject>;
      WatcherCancelled: TypedContractEvent<WatcherCancelledEvent.InputTuple, WatcherCancelledEvent.OutputTuple, WatcherCancelledEvent.OutputObject>;
    

      'WatcherScheduled(bytes32,uint256,uint256,uint32,uint32)': TypedContractEvent<WatcherScheduledEvent.InputTuple, WatcherScheduledEvent.OutputTuple, WatcherScheduledEvent.OutputObject>;
      WatcherScheduled: TypedContractEvent<WatcherScheduledEvent.InputTuple, WatcherScheduledEvent.OutputTuple, WatcherScheduledEvent.OutputObject>;
    
    };
  }