/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IExecutableWatcherInterface extends Interface {
    getFunction(nameOrSignature: "executeAnalysis" | "executeFetch"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'executeAnalysis', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'executeFetch', values: [BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'executeAnalysis', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeFetch', data: BytesLike): Result;
  }

  

  export interface IExecutableWatcher extends BaseContract {
    
    connect(runner?: ContractRunner | null): IExecutableWatcher;
    waitForDeployment(): Promise<this>;

    interface: IExecutableWatcherInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    executeAnalysis: TypedContractMethod<
      [executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    executeFetch: TypedContractMethod<
      [executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'executeAnalysis'): TypedContractMethod<
      [executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeFetch'): TypedContractMethod<
      [executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }