/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockRitualPrecompileInterface extends Interface {
    getFunction(nameOrSignature: "setResponse" | "setRevert"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'setResponse', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setRevert', values: [string]): string;

    decodeFunctionResult(functionFragment: 'setResponse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRevert', data: BytesLike): Result;
  }

  

  export interface MockRitualPrecompile extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockRitualPrecompile;
    waitForDeployment(): Promise<this>;

    interface: MockRitualPrecompileInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    setResponse: TypedContractMethod<
      [newResponse: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRevert: TypedContractMethod<
      [message: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'setResponse'): TypedContractMethod<
      [newResponse: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRevert'): TypedContractMethod<
      [message: string, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }