/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockSchedulerInterface extends Interface {
    getFunction(nameOrSignature: "callStates" | "cancel" | "cancelledCalls" | "cancelledCallsLength" | "executeAnalysis" | "executeFetch" | "getCallState" | "getScheduledCall" | "nextCallId" | "schedule" | "setCallState"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'callStates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelledCalls', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelledCallsLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeAnalysis', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'executeFetch', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'getCallState', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getScheduledCall', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextCallId', values?: undefined): string;
encodeFunctionData(functionFragment: 'schedule', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'setCallState', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'callStates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelledCalls', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelledCallsLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeAnalysis', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeFetch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCallState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getScheduledCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextCallId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'schedule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCallState', data: BytesLike): Result;
  }

  

  export interface MockScheduler extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockScheduler;
    waitForDeployment(): Promise<this>;

    interface: MockSchedulerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    callStates: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    cancel: TypedContractMethod<
      [callId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelledCalls: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    cancelledCallsLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    executeAnalysis: TypedContractMethod<
      [watcher: AddressLike, executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    executeFetch: TypedContractMethod<
      [watcher: AddressLike, executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getCallState: TypedContractMethod<
      [callId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getScheduledCall: TypedContractMethod<
      [callId: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string] & {data: string, gasLimit: bigint, startBlock: bigint, numCalls: bigint, frequency: bigint, ttl: bigint, maxFeePerGas: bigint, maxPriorityFeePerGas: bigint, value: bigint, payer: string }],
      'view'
    >
    

    
    nextCallId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    schedule: TypedContractMethod<
      [data: BytesLike, gasLimit: BigNumberish, startBlock: BigNumberish, numCalls: BigNumberish, frequency: BigNumberish, ttl: BigNumberish, maxFeePerGas: BigNumberish, maxPriorityFeePerGas: BigNumberish, value: BigNumberish, payer: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    setCallState: TypedContractMethod<
      [callId: BigNumberish, state: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'callStates'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancel'): TypedContractMethod<
      [callId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelledCalls'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelledCallsLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'executeAnalysis'): TypedContractMethod<
      [watcher: AddressLike, executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeFetch'): TypedContractMethod<
      [watcher: AddressLike, executionIndex: BigNumberish, assetId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCallState'): TypedContractMethod<
      [callId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getScheduledCall'): TypedContractMethod<
      [callId: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string] & {data: string, gasLimit: bigint, startBlock: bigint, numCalls: bigint, frequency: bigint, ttl: bigint, maxFeePerGas: bigint, maxPriorityFeePerGas: bigint, value: bigint, payer: string }],
      'view'
    >;
getFunction(nameOrSignature: 'nextCallId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'schedule'): TypedContractMethod<
      [data: BytesLike, gasLimit: BigNumberish, startBlock: BigNumberish, numCalls: BigNumberish, frequency: BigNumberish, ttl: BigNumberish, maxFeePerGas: BigNumberish, maxPriorityFeePerGas: BigNumberish, value: BigNumberish, payer: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCallState'): TypedContractMethod<
      [callId: BigNumberish, state: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }