/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRitualWallet, IRitualWalletInterface } from "../../ScheduledMarketWatcher.sol/IRitualWallet.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "lockDuration",
        "type": "uint256"
      }
    ],
    "name": "deposit",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class IRitualWallet__factory {
    static readonly abi = _abi;
    static createInterface(): IRitualWalletInterface {
      return new Interface(_abi) as IRitualWalletInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRitualWallet {
      return new Contract(address, _abi, runner) as unknown as IRitualWallet;
    }
  }
  